import {
    Home, User, Users, Mail, Phone, Calendar, Clock, Bell, Star, Heart,
    Bookmark, Tag, Flag, Award, Zap, Globe, MapPin, Building, Briefcase,
    Layout, Grid, Search, ExternalLink, Plus, Minus, X, Check, Edit,
    Trash2, Copy, Download, Upload, RefreshCw, Settings, MoreHorizontal,
    MessageSquare, MessageCircle, Send, Share, Smile, Frown, ThumbsUp,
    ThumbsDown, CheckCircle, XCircle, AlertCircle, AlertTriangle, Info,
    HelpCircle, TrendingUp, TrendingDown, BarChart2, PieChart, Activity,
    Target, File, FileText, Folder, Image, Video, Link, ShoppingCart,
    CreditCard, DollarSign, Percent, Receipt, Package, Truck, Lock,
    Unlock, Shield, Key, Eye, ChevronRight, ChevronLeft, ChevronUp, ChevronDown
} from 'lucide-react';

export const ICON_CATEGORIES = {
    'Navigation': [
        { name: 'Home', component: Home },
        { name: 'Layout', component: Layout },
        { name: 'Grid', component: Grid },
        { name: 'Search', component: Search },
        { name: 'ExternalLink', component: ExternalLink },
        { name: 'ChevronRight', component: ChevronRight },
        { name: 'ChevronLeft', component: ChevronLeft },
        { name: 'ChevronUp', component: ChevronUp },
        { name: 'ChevronDown', component: ChevronDown },
    ],
    'Actions': [
        { name: 'Plus', component: Plus },
        { name: 'Minus', component: Minus },
        { name: 'X', component: X },
        { name: 'Check', component: Check },
        { name: 'Edit', component: Edit },
        { name: 'Trash2', component: Trash2 },
        { name: 'Copy', component: Copy },
        { name: 'Download', component: Download },
        { name: 'Upload', component: Upload },
        { name: 'RefreshCw', component: RefreshCw },
        { name: 'Settings', component: Settings },
        { name: 'MoreHorizontal', component: MoreHorizontal },
    ],
    'Communication': [
        { name: 'Mail', component: Mail },
        { name: 'Phone', component: Phone },
        { name: 'MessageSquare', component: MessageSquare },
        { name: 'MessageCircle', component: MessageCircle },
        { name: 'Send', component: Send },
        { name: 'Share', component: Share },
        { name: 'Bell', component: Bell },
    ],
    'Users': [
        { name: 'User', component: User },
        { name: 'Users', component: Users },
        { name: 'Smile', component: Smile },
        { name: 'Frown', component: Frown },
        { name: 'ThumbsUp', component: ThumbsUp },
        { name: 'ThumbsDown', component: ThumbsDown },
    ],
    'Status': [
        { name: 'CheckCircle', component: CheckCircle },
        { name: 'XCircle', component: XCircle },
        { name: 'AlertCircle', component: AlertCircle },
        { name: 'AlertTriangle', component: AlertTriangle },
        { name: 'Info', component: Info },
        { name: 'HelpCircle', component: HelpCircle },
    ],
    'Charts': [
        { name: 'TrendingUp', component: TrendingUp },
        { name: 'TrendingDown', component: TrendingDown },
        { name: 'BarChart2', component: BarChart2 },
        { name: 'PieChart', component: PieChart },
        { name: 'Activity', component: Activity },
        { name: 'Target', component: Target },
    ],
    'Files': [
        { name: 'File', component: File },
        { name: 'FileText', component: FileText },
        { name: 'Folder', component: Folder },
        { name: 'Image', component: Image },
        { name: 'Video', component: Video },
        { name: 'Link', component: Link },
    ],
    'Commerce': [
        { name: 'ShoppingCart', component: ShoppingCart },
        { name: 'CreditCard', component: CreditCard },
        { name: 'DollarSign', component: DollarSign },
        { name: 'Percent', component: Percent },
        { name: 'Receipt', component: Receipt },
        { name: 'Package', component: Package },
        { name: 'Truck', component: Truck },
    ],
    'Security': [
        { name: 'Lock', component: Lock },
        { name: 'Unlock', component: Unlock },
        { name: 'Shield', component: Shield },
        { name: 'Key', component: Key },
        { name: 'Eye', component: Eye },
    ],
    'Date & Time': [
        { name: 'Calendar', component: Calendar },
        { name: 'Clock', component: Clock },
    ],
    'Misc': [
        { name: 'Star', component: Star },
        { name: 'Heart', component: Heart },
        { name: 'Bookmark', component: Bookmark },
        { name: 'Tag', component: Tag },
        { name: 'Flag', component: Flag },
        { name: 'Award', component: Award },
        { name: 'Zap', component: Zap },
        { name: 'Globe', component: Globe },
        { name: 'MapPin', component: MapPin },
        { name: 'Building', component: Building },
        { name: 'Briefcase', component: Briefcase },
    ],
};

export const ALL_ICONS = Object.values(ICON_CATEGORIES).flat();
